Update hosting_providers.json
certbot/website pull request #649
Opened 2020-09-28 22:56 UTC by sitedata

Add Rad Web Hosting

2020-09-29 17:13 UTC, ohemorange requested changes

2020-09-29 17:13 UTC, ohemorange commented on _data/hosting_providers.json
> +      {
```suggestion
  {
```

2020-09-29 17:13 UTC, ohemorange commented on _data/hosting_providers.json
> +    "category": "full",
Since the user has to run an explicit command, this is what we call "partial" support.
```suggestion
    "category": "partial",
```

2020-09-30 01:05 UTC, ohemorange commented on _data/hosting_providers.json
> +      {
please note the second suggestion

2020-09-30 01:16 UTC, sitedata commented on _data/hosting_providers.json
> +      {
Applied

2020-09-30 18:37 UTC, ohemorange approved these changes
Thank you!

2020-09-30 18:37 UTC, merged