Update hosting_providers.json
certbot/website pull request #671
Opened 2020-11-11 16:18 UTC by BoryaGames

I am added hosting 7m.pl

2020-11-11 20:54 UTC, alexzorin requested changes
Hi @BoryaGames,

Could you please clarify whether the hosting provider provides automatic HTTPS for custom domains as well, not only for `*.7m.pl`? If so, are there any example domains?

2020-11-11 20:54 UTC, alexzorin commented on _data/hosting_providers.json
> +    "reviewed": "",
```suggestion
    "reviewed": "2020.11.12",
```

2020-11-12 10:31 UTC, BoryaGames commented
> Hi @BoryaGames,
> 
> Could you please clarify whether the hosting provider provides automatic HTTPS for custom domains as well, not only for `*.7m.pl`? If so, are there any example domains?

Yes, but i am don't know example domains.

2020-11-13 07:51 UTC, alexzorin commented
I wasn't able to verify that HTTPS for custom domains is supported, so I sent the provider an email. I received a response:

>We don't currently offer https for domains, but it will be available soon.

I think the appropriate thing to do here would be to wait for this feature to be implemented.

2023-02-01 17:31 UTC, closed without merging