instructions: add #wildcard anchor parameter
certbot/website pull request #679
Opened 2020-12-08 09:15 UTC by alexzorin

When this anchor parameter is present, the instruction generator will
automatically select the "Wildcard" tab.

Supported URLs:

- `/#gentoo-nginx,wildcard` (persists on redirect)
- `/#wildcard` (persists after OS/server chosen and page redirects)
- `/lets-encrypt/gentoo-nginx#wildcard` (tab selected on load)

---
Unblocks https://github.com/certbot/certbot/pull/8479.

Also fixes https://github.com/certbot/website/issues/573. (Sort of. It won't automatically append `#wildcard` to the URL if you manually click the tab but you can manually type out the anchor).

Jamming it into the anchor like this is a little but crufty. Do we intend to keep supporting this URL scheme ~forever?

2020-12-10 16:45 UTC, bmw commented
@adferrand, if you have the time and interest to review this, that would be helpful.

If not, no worries.

2020-12-16 19:27 UTC, adferrand requested changes
Here are my comments about the current approach.

The code works, however I think that it is quite brittle to parse manually an anchor. Why not using URL parameters, like `/?os=gentoo&ws=nginx&wildcard`? This way we could use the standard `URL` or `URLSearchParams` to let the browser parse it for us.

If compatibility with IE is desired, we can use a polyfill like this one: https://unpkg.com/@ungap/url-search-params

2020-12-16 19:27 UTC, adferrand commented on _scripts/instruction-widget/main.js
> +    if (anchor_params.wildcard === true) {
You can use directly `if (anchor_params.wildcard)` here.

2020-12-16 20:16 UTC, alexzorin commented
Thanks for the review @adferrand.

>Why not using URL parameters, like /?os=gentoo&ws=nginx&wildcard? This way we could use the standard URL or URLSearchParams to let the browser parse it for us.

I agree that using the URL query is the superior day 1 solution.

The reason for my having done it this way is that the website [already uses URL fragment parsing](https://github.com/certbot/website/blob/ba943ae4c5cfafe0a3d1ffbdad0cb63c29b4fcff/_scripts/instruction-widget/main.js#L92-L94) in order to implement navigation, e.g. https://certbot.eff.org/#ubuntuxenial-apache, which it needs to continue to support.

This change extends that existing scheme to support flags.

 If doing so is too icky, I am happy to accept that and we can punt this whole thing to the next website rewrite. It's not critical to merge this, I just thought it might be easy.

2020-12-16 21:44 UTC, adferrand commented
Ok, if the anchors are used, it certainly the best thing to do to continue with it for now.

In the long term I think the website will benefit from a good refactoring. Given the number of javascript files, the site became too much dynamic for Jekyll, certainly here a proper javascript framework would be a smart move.

2020-12-17 04:42 UTC, alexzorin commented on _scripts/instruction-widget/main.js
> +    anchor_params = parse_anchor(window.location.hash);
It is used also by `get_input` which in turn can be triggered by a couple of DOM events. It seemed appropriate to save reparsing by adding a little state.

2020-12-17 04:49 UTC, alexzorin commented
The build is broken because of #685.

2020-12-17 07:47 UTC, adferrand commented on _scripts/instruction-widget/main.js
> +    anchor_params = parse_anchor(window.location.hash);
Global variables are really an anti-pattern in Javascript to solve this kind of problem, but given the absence of a proper framework to handle the state, I will not fight against the overall design in this case ;)

2020-12-17 10:47 UTC, adferrand approved these changes

2020-12-18 01:09 UTC, merged