Combell offers full HTTPS support
certbot/website pull request #683
Opened 2020-12-16 19:00 UTC by cedricdubois

HTTPS supported and automatically enabled on all shared hosting accounts

2020-12-16 20:56 UTC, alexzorin requested changes
Thank you! Just one small change.

2020-12-16 20:56 UTC, alexzorin commented on _data/hosting_providers.json
>      "reviewed": "",
```suggestion
    "reviewed": "2020.12.17",
```

2020-12-17 06:46 UTC, cedricdubois commented
Done, thanks!

2020-12-17 09:08 UTC, alexzorin commented
Closing and re-opening because CI was broken, but LGTM.

2020-12-17 09:19 UTC, alexzorin approved these changes

2020-12-17 09:20 UTC, merged