Add Clausweb to hosting providers
certbot/website pull request #697
Opened 2021-02-19 13:26 UTC by Vudubond

2021-02-20 01:45 UTC, ohemorange requested changes
This is great, thanks for supporting encryption on the web! I have a couple minor fixes, but otherwise looks good to go.

2021-02-20 01:45 UTC, ohemorange commented on _data/hosting_providers.json
>    }
```suggestion
  },
```

2021-02-20 01:45 UTC, ohemorange commented on _data/hosting_providers.json
> +   {
```suggestion
  {
```

2021-02-20 01:45 UTC, ohemorange commented on _data/hosting_providers.json
> +    "reviewed": "2019.5.31",
```suggestion
    "reviewed": "2020.2.19",
```

2021-02-24 20:18 UTC, Vudubond commented
Changes have been made.

2021-02-26 13:08 UTC, Vudubond reviewed
Changes made.

2021-02-26 23:47 UTC, ohemorange approved these changes
looks great, thank you!

2021-02-26 23:48 UTC, merged