pip: remove the snap in addition to OS packages
certbot/website pull request #726
Opened 2021-07-30 06:37 UTC by alexzorin

Some minor editors to the instructions to:

- Ask the user to remove the Certbot snap in addition to OS packages and certbot-auto
- Remove some irrelevant copy ("... before installing the Certbot snap ...").

This [came up](https://community.letsencrypt.org/t/error-access-denied-to-install-certbot-dns-cloudflare/156775/10?u=_az) on the forums. I guess some users will move from `snapd` to `pip` on occasion. It especially makes sense if they want a third-party plugin which isn't snapped.

![image](https://user-images.githubusercontent.com/311534/127611336-2d31ece6-7768-4b11-8c35-b4fdffda479c.png)

2021-08-03 00:00 UTC, ohemorange requested changes
Thanks for the PR, added some oxford commas but otherwise lgtm

2021-08-03 00:00 UTC, ohemorange commented on _scripts/instruction-widget/templates/install/pip.html
> +    <code>sudo dnf remove certbot</code> or <code>sudo snap remove certbot</code>.
```suggestion
    <code>sudo dnf remove certbot</code>, or <code>sudo snap remove certbot</code>.
```

2021-08-03 00:41 UTC, alexzorin commented
One day I will read a grammar guide :) .

2021-08-03 19:36 UTC, Polash2003 approved these changes

2021-08-31 23:40 UTC, bmw commented
Closing and reopening to trigger CI.

2022-07-13 22:26 UTC, ohemorange commented
This code is no longer being tracked on this repo, but I'll send the suggestions over to the team that owns the codebase now.

2023-02-16 22:16 UTC, closed without merging