Add Interhost Networks Company to the list
certbot/website pull request #782
Opened 2022-12-01 13:08 UTC by interhost7

2022-12-02 15:04 UTC, bmw requested changes

2022-12-02 15:04 UTC, bmw commented on _data/hosting_providers.json
> +    "category": "full",
I think this should be partial based on our descriptions at https://certbot.eff.org/hosting_providers/ and the tutorial you included.
```suggestion
    "category": "partial",
```

2022-12-02 15:04 UTC, bmw commented on _data/hosting_providers.json
> +    "plan": "https://interhost.co.il/servers-services/cloud-services/virtual-servers/",
Per https://github.com/certbot/website#hosting-providers-list, this link isn't going to show up so I think we should just remove it.
```suggestion
    "plan": "",
```

2022-12-04 06:58 UTC, interhost7 commented
Hi, 
Thank you for the suggestions. We have fixed the fields, please review again.

2022-12-05 15:04 UTC, bmw approved these changes
Great. Thanks! This LGTM.

2022-12-05 15:04 UTC, merged